version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /
hooks:
  ApplicationStop:
    - location: scripts/StopApache
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/InstallApache.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/StartApache.sh
      timeout: 180
      runas: root
