version: 0.2
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - aws s3 cp dist s3://brcornelius --recursive
            - echo Build completed
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes