version: 0.2
env:
    secrets-manager:
        secret_api_key: corneliuses-api-key:x-api-key
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - echo $secret_api_key
            - ng build --prod
    post_build:
         commands:
            - aws s3 cp dist/brian s3://brian.corneliuses.com --recursive
            - echo Build completed
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes